### ISSUE TITLE
魚客松是什麼？

### ISSUE THREAD

**Issue by ghost** [twaic/fishackathon-taipei#10]
魚客松是什麼？WHAT IS A FISHACKATHON?

**Comment by CrystalTu** [comment]
魚客松一個全球共同舉行的活動，希望能夠透過科技來解決永續漁業的難題～

**Comment by twaic-amspaces** [comment]
A Fishackathon is a computer coding and other technology intensive event, or hackathon that takes place over a weekend. At the hackathon, developers, designers, project managers, and subject matter experts come together to create applications, systems, and tools for sustainable fishery issues.
