### ISSUE TITLE
魚客松的產出作品會被怎麼使用？

### ISSUE THREAD

**Issue by ghost** [twaic/fishackathon-taipei#11]
WHAT WILL BE DONE WITH THE APPLICATIONS THAT ARE CREATED BY THE HACKERS?

**Comment by twaic-amspaces** [comment]
Any and all works created during the Fishackathon are developed under [the Creative Commons Attribution-ShareAlike 4.0 International License legalcode](https://creativecommons.org/licenses/by-sa/4.0/legalcode). The organizations and individuals who submitted problem statements may continue to work with the Fishackathon teams who worked on their respective problem statements to fully develop the ideas and ideally see them through to implementation.

在魚客松活動所開發的所有作品必須同意採用「創用CC授權條款」的  CC-BY-SA 4.0 規範 (Creative Commons Attribution-ShareAlike 4.0 International License)。
