### ISSUE TITLE
請問鯉魚裡面的所需資訊在哪裡？

### ISSUE THREAD

**Issue by ghost** [twaic/fishackathon-taipei#20]
網頁連結裡只看得到水位高度，謝謝!

**Comment by CrystalTu** [comment]
詢問加拿大DFO中，稍候會更新......

**Comment by cielocot** [comment]
我們正在問美國的主辦單位中，請稍等

**Comment by cielocot** [comment]
五大湖水溫資料：
http://www.glerl.noaa.gov/res/glcfs/glcfs.php?lake=s&ext=swt&type=N&hr=00

水文數據資料庫：
http://www.glerl.noaa.gov/ftp/publications/tech_reports/glerl-083/UpdatedFiles/

正在等加拿大DFO確認是否有別的資料庫

**Comment by cielocot** [comment]
更新版的problem statement，裡面有新的連結(在整份文件的最後兩頁)：

https://docs.google.com/document/d/13BIMKfD85aka9V1NjgXlTd9DQekuQ1ZCMUrIZG0yr6Y/edit?usp=sharing
