### ISSUE TITLE
鯉魚資料的樣點

### ISSUE THREAD

**Issue by iridovirus** [twaic/fishackathon-taipei#22]
請問鯉魚資料樣點的位置或座標再哪?

**Comment by cielocot** [comment]
請參考更新後的Problem Statement，其後附的資料連結有流速資料，不再需要那三個公式去轉換流量&流速

https://docs.google.com/document/d/13BIMKfD85aka9V1NjgXlTd9DQekuQ1ZCMUrIZG0yr6Y/edit
