### ISSUE TITLE
請問鯉魚之中之實際河道長度

### ISSUE THREAD

**Issue by yueming-Chen** [twaic/fishackathon-taipei#25]
請問鯉魚中之manrake lab有無提供參考資料去取得實際河道場度?
此外在asian carp的detection site是否有特定鯉魚去套用到特定的溪流長度，亦或是只需要求出最低的距離即為此次的預測值?

**Comment by cielocot** [comment]
請參考更新後的Problem Statement，第4點（在新版中為第三點）已修正為：
https://docs.google.com/document/d/13BIMKfD85aka9V1NjgXlTd9DQekuQ1ZCMUrIZG0yr6Y/edit
1. Compare the required river length to the actual river length to the first barrier. Measure distance of river between the Great lakes and the first dam or waterfall using GoogleEarth.

估算溪流長度用的incubation time 可以參考表一，每個魚種不一樣
