### ISSUE TITLE
哪裡可以找到很多魚的照片?

### ISSUE THREAD

**Issue by CrystalTu** [twaic/fishackathon-taipei#30]
1. Fishbase.org
2. ARKiv.org

**Comment by a314172427a** [comment]
http://fishdb.sinica.edu.tw/
中研院~台灣漁業資料庫

**Comment by cielocot** [comment]
加拿大的魚
http://www.dfo-mpo.gc.ca/species-especes/aquatic-aquatique/browse-consultez-eng.htm

**Comment by Chijuyu** [comment]
這個魚類分類網站也很有趣是澳洲釣客釣到的魚可以依照部位、體色等特徵查詢種名的
http://getfishing.com.au/resources/fish-identification/

**Comment by cielocot** [comment]
FDA的網站

http://www.fda.gov/Food/FoodScienceResearch/RFE/ucm064456.htm
