### ISSUE TITLE
有關出題範圍三「幫助漁民最大化他們的漁獲價值」疑問

### ISSUE THREAD

**Issue by ghost** [twaic/fishackathon-taipei#9]
幫助漁民最大化他們的漁獲價值，這是不是違反環境永續的主題？是類似高經濟作物的意思？

**Comment by Shang-ju** [comment]
魚多魚土，抓越多反而價值越低

**Comment by twaic-amspaces** [comment]
From Washington:
By maximize the value of their catch that means quality fish over quantity. Also, fish that are large enough to be caught rather than catching those not fully grown yet.
